version: '3'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3100:3000"
    networks:
      - default
      - webfront
    labels:
      caddy: quiz.martingschneider.de
      caddy.reverse_proxy: "{{upstreams 3000}}"
      caddy.log: ""
      caddy.header: Strict-Transport-Security "max-age=31536000;"
    volumes:
      - .:/usr/src/app
      - '/usr/src/app/node_modules'
      - '/usr/src/app/.next'
    environment:
      - NODE_ENV=production
    command: npm run start

networks:
  webfront:
    external: true
